language: java

jdk:
  - openjdk8

services: mongodb

before_script:
    - mongo mydb --eval 'db.createUser({user:"myusername",pwd:"mypassword",roles:["readWrite"]});'

script: mvn clean install

after_success:
  - bash <(curl -s https://codecov.io/bash)
  - mvn cobertura:cobertura
